// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDiscard() {
  return window['go']['main']['App']['ConfirmDiscard']();
}

export function GetCSS() {
  return window['go']['main']['App']['GetCSS']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWelcome() {
  return window['go']['main']['App']['GetWelcome']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OnFileDrop(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnFileDrop'](arg1, arg2, arg3);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function Render(arg1) {
  return window['go']['main']['App']['Render'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetTitle(arg1) {
  return window['go']['main']['App']['SetTitle'](arg1);
}
