// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function ConfirmDiscard():Promise<boolean>;

export function GetCSS():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetWelcome():Promise<string>;

export function LoadFile(arg1:string):Promise<string>;

export function OnFileDrop(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function QuitApp():Promise<void>;

export function Render(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTitle(arg1:string):Promise<void>;
