// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetCSS() {
  return window['go']['main']['App']['GetCSS']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetWelcome() {
  return window['go']['main']['App']['GetWelcome']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OnFileDrop(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnFileDrop'](arg1, arg2, arg3);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Render(arg1) {
  return window['go']['main']['App']['Render'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetMath(arg1) {
  return window['go']['main']['App']['SetMath'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWordWrap(arg1) {
  return window['go']['main']['App']['SetWordWrap'](arg1);
}

export function SetTitle(arg1) {
  return window['go']['main']['App']['SetTitle'](arg1);
}
